package enums;

public enum AddBook {
    ADDED_SUCCESSFULLY,
    NEW_ADDED_SUCCESSFULLY,
    LIBRARY_IS_FULL,
    NO_OTHER_BOOK_TO_ADD,
    BELONG_TO_ANOTHER_LIBRARY,
    BOOK_NEVER_EXIST,
    LIBRARY_NEVER_EXIST;
}
